source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'

target 'AutomationTools_Example' do
  pod 'AutomationTools-Host', :path => '../'
end

target 'AutomationTools_Tests' do
  pod 'AutomationTools-Core', :path => '../'
end
